# Generated by Django 4.2.23 on 2025-08-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
